# ==========================================
# Stable Rules (Works with standard 'cargo fmt')
# ==========================================

comment_width = 80
wrap_comments = true

newline_style = "Unix"

trailing_comma = "Vertical"


# ==========================================
# Nightly Rules
# ==========================================

# Required to unlock advanced features below
unstable_features = true

# 1. Merge imports from the same crate into a single nested line
imports_granularity = "Crate"

# 2. Automatically group imports into 3 neat blocks:
group_imports = "StdExternalCrate"

# 3. Alphabetically sort your imports inside those groups
reorder_imports = true
